experiment:
  meta:
    name: "GATE_Cora_Experiment_1"
  model:
    family: "GAT"
  training:
    num_epochs: 10
    node_features: 1433
    n_classes: 7
    n_hidden: 64
    n_heads: 2
    dropout: 0
    learning_rate: 0.001
  save:
    save_path: "saved_models"
