experiment:
  meta:
    name: "GAT_BACE_Experiment_1"
  model:
    family: "GAT"
  training:
    num_epochs: 100
    node_features: 9
    n_classes: 1
    n_hidden: 32
    n_heads: 2
    dropout: 0
    learning_rate: 0.0001
  save:
    save_path: "saved_models"
